//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointmentSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int id { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<int> PNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Gender { get; set; }
    }
}
