//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointmentSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_admin
    {
        public string DOCTOR { get; set; }
        public string DOCTOR_GENDER { get; set; }
        public Nullable<int> DOCTOR_Phone { get; set; }
        public string PATIENT { get; set; }
        public string Gender { get; set; }
        public Nullable<int> PNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
